frr version 8.4
frr defaults traditional
hostname pe4
service integrated-vtysh-config
!
mpls label dynamic-block 240000 249999
!
interface lo
 ip address 2.2.2.4/32
!
interface eth1
 ip address 10.100.1.61/30
 ip ospf area 0
!
interface eth2
 description Connection to hub-b
!
interface eth2.10
 vrf Launch_Ops
 ip address 172.16.10.14/30
!
interface eth2.20
 vrf Sat_Ops
 ip address 172.16.20.14/30
!
interface eth2.30
 vrf Tracking
 ip address 172.16.30.14/30
!
interface eth2.40
 vrf Admin
 ip address 172.16.40.14/30
!
!
router ospf
 ospf router-id 2.2.2.4
 network 2.2.2.4/32 area 0
 network 10.100.1.0/24 area 0
!
mpls ldp
 router-id 2.2.2.4
 !
 address-family ipv4
  discovery transport-address 2.2.2.4
  !
  interface eth1
  !
 exit-address-family
!
router bgp 65001
 bgp router-id 2.2.2.4
 no bgp default ipv4-unicast
 neighbor PE_PEERS peer-group
 neighbor PE_PEERS remote-as 65001
 neighbor PE_PEERS update-source lo
 neighbor 2.2.2.1 peer-group PE_PEERS
 neighbor 2.2.2.2 peer-group PE_PEERS
 neighbor 2.2.2.3 peer-group PE_PEERS
 neighbor 2.2.2.5 peer-group PE_PEERS
 neighbor 2.2.2.6 peer-group PE_PEERS
 !
 address-family vpnv4 unicast
  neighbor PE_PEERS activate
 exit-address-family
!
router bgp 65001 vrf Launch_Ops
 rd 65001:10
 route-target import 65001:10
 route-target export 65001:10
 !
 address-family ipv4 unicast
  redistribute connected
  redistribute static
 exit-address-family
!
router bgp 65001 vrf Sat_Ops
 rd 65001:20
 route-target import 65001:20
 route-target export 65001:20
 !
 address-family ipv4 unicast
  redistribute connected
  redistribute static
 exit-address-family
!
router bgp 65001 vrf Tracking
 rd 65001:30
 route-target import 65001:30
 route-target export 65001:30
 !
 address-family ipv4 unicast
  redistribute connected
  redistribute static
 exit-address-family
!
router bgp 65001 vrf Admin
 rd 65001:40
 route-target import 65001:40
 route-target export 65001:40
 !
 address-family ipv4 unicast
  redistribute connected
  redistribute static
 exit-address-family
!
ip route 192.168.5.0/24 172.16.10.13 vrf Launch_Ops
ip route 192.168.6.0/24 172.16.20.13 vrf Sat_Ops
ip route 192.168.7.0/24 172.16.30.13 vrf Tracking
ip route 192.168.8.0/24 172.16.40.13 vrf Admin
!
line vty
!
