frr version 8.4
frr defaults traditional
hostname p5
service integrated-vtysh-config
!
mpls label dynamic-block 150000 159999
!
interface lo
 ip address 1.1.1.5/32
 ip ospf area 0
!
interface eth1
 ip address 10.100.1.6/30
 ip ospf area 0
!
interface eth2
 ip address 10.100.1.37/30
 ip ospf area 0
!
interface eth3
 ip address 10.100.1.41/30
 ip ospf area 0
!
interface eth4
 ip address 10.100.1.58/30
 ip ospf area 0
!
!
router ospf
 ospf router-id 1.1.1.5
!
mpls ldp
 router-id 1.1.1.5
 !
 address-family ipv4
  discovery transport-address 1.1.1.5
  !
  interface eth1
  interface eth2
  interface eth3
  interface eth4
  !
 exit-address-family
!
line vty
!
