frr version 8.4
frr defaults traditional
hostname hub-d
service integrated-vtysh-config
!
interface lo
 ip address 3.3.3.5/32
!
interface eth1
 description Connection to PE pe6
!
interface eth1.10
 vrf Launch_Ops
 ip address 172.16.10.21/30
!
interface eth1.20
 vrf Sat_Ops
 ip address 172.16.20.21/30
!
interface eth1.30
 vrf Tracking
 ip address 172.16.30.21/30
!
interface eth1.40
 vrf Admin
 ip address 172.16.40.21/30
!
interface eth2
 vrf Launch_Ops
 ip address 192.168.13.254/24
!
interface eth3
 vrf Sat_Ops
 ip address 192.168.14.254/24
!
interface eth4
 vrf Tracking
 ip address 192.168.15.254/24
!
interface eth5
 vrf Admin
 ip address 192.168.16.254/24
!
!
ip route 0.0.0.0/0 172.16.10.22 vrf Launch_Ops
ip route 0.0.0.0/0 172.16.20.22 vrf Sat_Ops
ip route 0.0.0.0/0 172.16.30.22 vrf Tracking
ip route 0.0.0.0/0 172.16.40.22 vrf Admin
!
line vty
!
