frr version 8.4
frr defaults traditional
hostname pe2
service integrated-vtysh-config

interface lo
 ip address 22.22.22.22/32

interface eth1
 ip address 10.0.2.2/30

router ospf
 ospf router-id 22.22.22.22
 network 22.22.22.22/32 area 0
 network 10.0.2.0/30 area 0

line vty
