frr version 8.4
frr defaults traditional
hostname gs14
service integrated-vtysh-config
!
interface eth1
 description Connection to Hub hub-d
 ip address 192.168.14.1/24
!
!
ip route 0.0.0.0/0 192.168.14.254
!
line vty
!
