frr version 8.4
frr defaults traditional
hostname p7
service integrated-vtysh-config
!
mpls label dynamic-block 170000 179999
!
interface lo
 ip address 1.1.1.7/32
 ip ospf area 0
!
interface eth1
 ip address 10.100.1.42/30
 ip ospf area 0
!
interface eth2
 ip address 10.100.1.34/30
 ip ospf area 0
!
interface eth3
 ip address 10.100.1.45/30
 ip ospf area 0
!
interface eth4
 ip address 10.100.1.66/30
 ip ospf area 0
!
!
router ospf
 ospf router-id 1.1.1.7
!
mpls ldp
 router-id 1.1.1.7
 !
 address-family ipv4
  discovery transport-address 1.1.1.7
  !
  interface eth1
  interface eth2
  interface eth3
  interface eth4
  !
 exit-address-family
!
line vty
!
