frr version 8.4
frr defaults traditional
hostname p2
service integrated-vtysh-config

interface lo
 ip address 2.2.2.2/32

interface eth1
 ip address 10.0.1.6/30

interface eth2
 ip address 10.0.1.10/30

interface eth3
 ip address 10.0.1.21/30

interface eth4
 ip address 10.0.1.25/30

router ospf
 ospf router-id 2.2.2.2
 network 2.2.2.2/32 area 0
 network 10.0.1.0/24 area 0

line vty
