frr version 8.4
frr defaults traditional
hostname hub-a
service integrated-vtysh-config
!
interface lo
 ip address 3.3.3.2/32
!
interface eth1
 description Connection to PE pe3
!
interface eth1.10
 vrf Launch_Ops
 ip address 172.16.10.9/30
!
interface eth1.20
 vrf Sat_Ops
 ip address 172.16.20.9/30
!
interface eth1.30
 vrf Tracking
 ip address 172.16.30.9/30
!
interface eth1.40
 vrf Admin
 ip address 172.16.40.9/30
!
interface eth2
 vrf Launch_Ops
 ip address 192.168.1.254/24
!
interface eth3
 vrf Sat_Ops
 ip address 192.168.2.254/24
!
interface eth4
 vrf Tracking
 ip address 192.168.3.254/24
!
interface eth5
 vrf Admin
 ip address 192.168.4.254/24
!
!
ip route 0.0.0.0/0 172.16.10.10 vrf Launch_Ops
ip route 0.0.0.0/0 172.16.20.10 vrf Sat_Ops
ip route 0.0.0.0/0 172.16.30.10 vrf Tracking
ip route 0.0.0.0/0 172.16.40.10 vrf Admin
!
line vty
!
