frr version 8.4
frr defaults traditional
hostname p1
service integrated-vtysh-config

interface lo
 ip address 1.1.1.1/32

interface eth1
 ip address 10.0.1.2/30

interface eth2
 ip address 10.0.1.9/30

interface eth3
 ip address 10.0.1.13/30

interface eth4
 ip address 10.0.1.17/30

router ospf
 ospf router-id 1.1.1.1
 network 1.1.1.1/32 area 0
 network 10.0.1.0/24 area 0

line vty
