frr version 8.4
frr defaults traditional
hostname pe1
service integrated-vtysh-config

interface lo
 ip address 11.11.11.11/32

interface eth2
 ip address 10.0.1.1/30

interface eth3
 ip address 10.0.1.5/30

router ospf
 ospf router-id 11.11.11.11
 network 11.11.11.11/32 area 0
 network 10.0.1.0/24 area 0

line vty
