frr version 8.4
frr defaults traditional
hostname p4
service integrated-vtysh-config
!
mpls label dynamic-block 140000 149999
!
interface lo
 ip address 1.1.1.4/32
!
interface eth1
 ip address 10.100.1.29/30
 ip ospf area 0
!
interface eth2
 ip address 10.100.1.33/30
 ip ospf area 0
!
interface eth3
 ip address 10.100.1.26/30
 ip ospf area 0
!
interface eth4
 ip address 10.100.1.49/30
 ip ospf area 0
!
!
router ospf
 ospf router-id 1.1.1.4
 network 1.1.1.4/32 area 0
 network 10.100.1.0/24 area 0
!
mpls ldp
 router-id 1.1.1.4
 !
 address-family ipv4
  discovery transport-address 1.1.1.4
  !
  interface eth1
  interface eth2
  interface eth3
  interface eth4
  !
 exit-address-family
!
line vty
!
