frr version 8.4
frr defaults traditional
hostname gs4
service integrated-vtysh-config
!
interface eth1
 description Connection to Hub hub-a
 ip address 192.168.4.1/24
!
!
ip route 0.0.0.0/0 192.168.4.254
!
line vty
!
