frr version 8.4
frr defaults traditional
hostname gs5
service integrated-vtysh-config
!
interface eth1
 description Connection to Hub hub-b
 ip address 192.168.5.1/24
!
!
ip route 0.0.0.0/0 192.168.5.254
!
line vty
!
