frr version 8.4
frr defaults traditional
hostname hub-c
service integrated-vtysh-config
!
interface lo
 ip address 3.3.3.4/32
!
interface eth1
 description Connection to PE pe5
!
interface eth1.10
 vrf Launch_Ops
 ip address 172.16.10.17/30
!
interface eth1.20
 vrf Sat_Ops
 ip address 172.16.20.17/30
!
interface eth1.30
 vrf Tracking
 ip address 172.16.30.17/30
!
interface eth1.40
 vrf Admin
 ip address 172.16.40.17/30
!
interface eth2
 vrf Launch_Ops
 ip address 192.168.9.254/24
!
interface eth3
 vrf Sat_Ops
 ip address 192.168.10.254/24
!
interface eth4
 vrf Tracking
 ip address 192.168.11.254/24
!
interface eth5
 vrf Admin
 ip address 192.168.12.254/24
!
!
ip route 0.0.0.0/0 172.16.10.18 vrf Launch_Ops
ip route 0.0.0.0/0 172.16.20.18 vrf Sat_Ops
ip route 0.0.0.0/0 172.16.30.18 vrf Tracking
ip route 0.0.0.0/0 172.16.40.18 vrf Admin
!
line vty
!
