frr version 8.4
frr defaults traditional
hostname p4
service integrated-vtysh-config

interface lo
 ip address 4.4.4.4/32

interface eth1
 ip address 10.0.1.18/30

interface eth2
 ip address 10.0.1.26/30

interface eth3
 ip address 10.0.1.30/30

interface eth4
 ip address 10.0.2.1/30

router ospf
 ospf router-id 4.4.4.4
 network 4.4.4.4/32 area 0
 network 10.0.1.0/24 area 0
 network 10.0.2.0/30 area 0

line vty
